name: anysongs
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  cupertino_icons: ^1.0.2
  just_audio: ^0.9.37
  just_audio_background: ^0.0.1-beta.11
  on_audio_query: ^2.9.0
  path_provider: ^2.1.1
  flutter_bloc: ^8.1.6
  easy_localization: ^3.0.5
  # app_settings: ^4.3.1
  # device_info_plus: ^9.1.2
  loading_animation_widget: ^1.2.1
  # glassmorphism_ui: ^0.3.0
  permission_handler: ^11.3.1
  stream_transform: ^2.1.0
  rxdart: ^0.27.7
  hive_flutter:
  palette_generator: ^0.3.3+3
  marquee: ^2.2.3
  sqflite: ^2.3.3+1
dependency_overrides:
  fading_edge_scrollview: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1


flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - assets/translations/

        
    
    
                                      